# Generated by Django 5.2.12 on 2026-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stream_url', models.URLField(help_text='RTSP or HLS stream URL.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CCTV Camera',
                'verbose_name_plural': 'CCTV Cameras',
                'ordering': ['name'],
            },
        ),
    ]
