# Generated by Django 5.2.12 on 2026-03-14 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionalert',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cameras.cctvcamera'),
        ),
    ]
